// generated by: nest g service notification/channels/email-channel
import { Injectable } from '@nestjs/common';
import { INotificationChannel } from '../../../shared/interfaces/notification-channels.interface';
import { CHANNEL_TYPES } from '../channels.constants';

@Injectable()
export class EmailChannelService implements INotificationChannel {
  getChannelType(): string {
    return CHANNEL_TYPES.EMAIL;
  } 

  sendNotification(payload: any): string {
    console.log('Sending Email Notification:', payload);
    return 'Notification sent to Email';
  }
}
